
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Principal extends javax.swing.JFrame {
    
    public Principal() {
        initComponents();
        ab = new adminBarra(pg_1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Crear_Usuario = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bt_Crear_PErsona = new javax.swing.JButton();
        tf_Nombre = new javax.swing.JTextField();
        tf_Apellido = new javax.swing.JTextField();
        tf_Usuario1 = new javax.swing.JTextField();
        tf_WIFI = new javax.swing.JTextField();
        pf_Contraseña_1 = new javax.swing.JPasswordField();
        tf_Telefono = new javax.swing.JTextField();
        jd_Interfaz_Usuario = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_amigos = new javax.swing.JList();
        pg_1 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_Usuarios = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_Chats = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        tf_Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pf_Clave = new javax.swing.JPasswordField();
        bt_Crear_Usuario = new javax.swing.JButton();
        bt_Entrar = new javax.swing.JButton();
        bt_Chat = new javax.swing.JButton();

        jd_Crear_Usuario.setTitle("Creacion de Usuario");

        jLabel3.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Usuario");

        jLabel7.setText("Contraseña");

        jLabel9.setText("Calidad de Wifi");

        jLabel10.setText("Numero de Telefono");

        bt_Crear_PErsona.setText("Crear");
        bt_Crear_PErsona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_PErsonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_Crear_UsuarioLayout = new javax.swing.GroupLayout(jd_Crear_Usuario.getContentPane());
        jd_Crear_Usuario.getContentPane().setLayout(jd_Crear_UsuarioLayout);
        jd_Crear_UsuarioLayout.setHorizontalGroup(
            jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Crear_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Crear_UsuarioLayout.createSequentialGroup()
                        .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_Crear_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt_Crear_PErsona))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jd_Crear_UsuarioLayout.createSequentialGroup()
                        .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Crear_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pf_Contraseña_1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Crear_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(tf_WIFI))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Crear_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Usuario1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Crear_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Apellido))
                            .addGroup(jd_Crear_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jd_Crear_UsuarioLayout.setVerticalGroup(
            jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Crear_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(tf_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pf_Contraseña_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Crear_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_WIFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(bt_Crear_PErsona)
                .addGap(40, 40, 40))
        );

        jd_Interfaz_Usuario.setTitle("Interfaz Usuario");

        jLabel4.setText("Amigos");

        jl_amigos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_amigos);

        pg_1.setMaximum(100000000);

        jl_Usuarios.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_Usuarios);

        jLabel8.setText("Otros Usuarios");

        jLabel11.setText("Chat Creados");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Chats");
        jt_Chats.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_Chats);

        javax.swing.GroupLayout jd_Interfaz_UsuarioLayout = new javax.swing.GroupLayout(jd_Interfaz_Usuario.getContentPane());
        jd_Interfaz_Usuario.getContentPane().setLayout(jd_Interfaz_UsuarioLayout);
        jd_Interfaz_UsuarioLayout.setHorizontalGroup(
            jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Interfaz_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Interfaz_UsuarioLayout.createSequentialGroup()
                        .addGroup(jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(230, 230, 230)
                        .addGroup(jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pg_1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                            .addGroup(jd_Interfaz_UsuarioLayout.createSequentialGroup()
                                .addGroup(jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jd_Interfaz_UsuarioLayout.createSequentialGroup()
                        .addGroup(jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_Interfaz_UsuarioLayout.setVerticalGroup(
            jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Interfaz_UsuarioLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pg_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_Interfaz_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Interfaz_UsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_Interfaz_UsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leogram");

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        bt_Crear_Usuario.setText("Crear Usuario");
        bt_Crear_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_UsuarioActionPerformed(evt);
            }
        });

        bt_Entrar.setText("Entrar");
        bt_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EntrarActionPerformed(evt);
            }
        });

        bt_Chat.setText("Chat");
        bt_Chat.setEnabled(false);
        bt_Chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pf_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_Entrar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Crear_Usuario))
                    .addComponent(bt_Chat))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pf_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Entrar)
                    .addComponent(bt_Crear_Usuario))
                .addGap(18, 18, 18)
                .addComponent(bt_Chat)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Crear_PErsonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_PErsonaActionPerformed
        // TODO add your handling code here:
        us = new Usuario(tf_Usuario1.getText(), pf_Contraseña_1.getText(), Integer.parseInt(tf_WIFI.getText()), tf_Nombre.getText(), tf_Apellido.getText(), tf_Telefono.getText());
        String op = "s";
        String op1 = "s";
        while (op.equals("s")) {
            us.getAmigos().add(new Persona(JOptionPane.showInputDialog("Nombre del Amigo"), JOptionPane.showInputDialog("Apellido del Amigo"), JOptionPane.showInputDialog("Telefono del Amigo")));
            a++;
            op = JOptionPane.showInputDialog("Desea seguir agregando amigos s/n");
        }
        while (op.equals("s")) {
            us.getAmigos().add(new Persona(JOptionPane.showInputDialog("Nombre del Amigo"), JOptionPane.showInputDialog("Apellido del Amigo"), JOptionPane.showInputDialog("Telefono del Amigo")));
            op = JOptionPane.showInputDialog("Desea continuar s/n");
        }//Fin del while de os amigos
        usuarios.add(us);
        ap = new AdminArchivo("./usuarios.cbm");
        ap.cargarArchivo();
        ap.setAlumno(us);
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Usuario guardado exitosamente");
        tf_Nombre.setText("");
        tf_Apellido.setText("");
        tf_Telefono.setText("");
        tf_Usuario1.setText("");
        tf_WIFI.setText("");
        pf_Contraseña_1.setText("");
    }//GEN-LAST:event_bt_Crear_PErsonaActionPerformed

    private void bt_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EntrarActionPerformed
        // TODO add your handling code here:
        AdminArchivo ap = new AdminArchivo("./usuarios.cbm");
        ap.cargarArchivo();
        Object[] usa;
        int cont = 0;
        usa = ap.getListaPersonas().toArray();
        for (int i = 0; i < usa.length; i++) {
            if (((Usuario) usa[i]).getUsuario().equals(tf_Usuario.getText()) && ((Usuario) usa[i]).getContrasenia().equals(pf_Clave.getText())) {
                bt_Chat.setEnabled(true);
                temp = tf_Usuario.getText();
                tf_Usuario.setText("");
                pf_Clave.setText("");
                JOptionPane.showMessageDialog(this, "Bienvenido");
            } else {
                cont++;
            }
        }
        if (cont > usa.length) {
            JOptionPane.showMessageDialog(this, "Algun dato ingresado esta malo o no existe ese usuario");
        }
    }//GEN-LAST:event_bt_EntrarActionPerformed

    private void bt_Crear_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_UsuarioActionPerformed
        // TODO add your handling code here:
        jd_Crear_Usuario.setModal(true);
        jd_Crear_Usuario.pack();
        jd_Crear_Usuario.setLocationRelativeTo(this);
        jd_Crear_Usuario.setVisible(true);
    }//GEN-LAST:event_bt_Crear_UsuarioActionPerformed

    private void bt_ChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ChatActionPerformed
        // TODO add your handling code here:
        jd_Interfaz_Usuario.setModal(true);
        jd_Interfaz_Usuario.pack();
        AdminArchivo ap = new AdminArchivo("./usuarios.cbm");
        ap.cargarArchivo();
        DefaultListModel modelo = (DefaultListModel) jl_amigos.getModel();
        Object[] usa;
        usa = ap.getListaPersonas().toArray();
        for (int i = 0; i < usa.length; i++) {
            modelo.addElement(((Usuario) usa[i]).getAmigos());
        }
        
        jl_amigos.setModel(modelo);
        jd_Interfaz_Usuario.setLocationRelativeTo(this);
        jd_Interfaz_Usuario.setVisible(true);
    }//GEN-LAST:event_bt_ChatActionPerformed
    public void arbol() {
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < usuarios.size(); i++) {
            modelo.addElement(usuarios.get(i));
        }
        jl_amigos.setModel(modelo);
        DefaultListModel modelo1 = new DefaultListModel();
        for (int i = 0; i < usuarios.get(a).getAmigos().size(); i++) {
            modelo1.addElement(usuarios.get(a).getAmigos().get(i));
        }
        DefaultTreeModel arbol = (DefaultTreeModel) jt_Chats.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) arbol.getRoot();
        for (int i = 0; i < usuarios.get(a).getChats().size(); i++) {
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(usuarios.get(a).getChats().get(i));
            if (usuarios.get(a).getChats().get(i) instanceof Privado) {
                ((DefaultMutableTreeNode) raiz.getChildAt(0)).add(p);
            } else if (usuarios.get(a).getChats().get(i) instanceof Grupo) {
                ((DefaultMutableTreeNode) raiz.getChildAt(1)).add(p);                
            }
            arbol.reload();;
        }
        jl_amigos.setModel(modelo1);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Chat;
    private javax.swing.JButton bt_Crear_PErsona;
    private javax.swing.JButton bt_Crear_Usuario;
    private javax.swing.JButton bt_Entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_Crear_Usuario;
    private javax.swing.JDialog jd_Interfaz_Usuario;
    private javax.swing.JList jl_Usuarios;
    private javax.swing.JList jl_amigos;
    private javax.swing.JTree jt_Chats;
    private javax.swing.JPasswordField pf_Clave;
    private javax.swing.JPasswordField pf_Contraseña_1;
    private javax.swing.JProgressBar pg_1;
    private javax.swing.JTextField tf_Apellido;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_Telefono;
    private javax.swing.JTextField tf_Usuario;
    private javax.swing.JTextField tf_Usuario1;
    private javax.swing.JTextField tf_WIFI;
    // End of variables declaration//GEN-END:variables
Usuario us = new Usuario();
    AdminArchivo ap;
    adminBarra ab;
    ArrayList solicitudes = new ArrayList();
    Privado p = new Privado();
    Grupo go = new Grupo();
    Object temp;
    int a = 0;
    ArrayList<Usuario> usuarios = new ArrayList();
}
